# .github/workflows/progress-check.yml

name: Progress Check

on:
  push:
    paths:
      - '**/weekly-progress.md'
  pull_request:
    paths:
      - '**/weekly-progress.md'

jobs:
  check-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Weekly Progress Structure
        run: |
          echo "Checking weekly progress files..."
          for file in $(find . -name "weekly-progress.md"); do
            echo "Checking $file"
            
            # Check for required sections
            if ! grep -q "^## Week " "$file"; then
              echo "Error: $file is missing Week section"
              exit 1
            fi
            
            if ! grep -q "### Learning Objectives" "$file"; then
              echo "Error: $file is missing Learning Objectives section"
              exit 1
            fi
            
            if ! grep -q "### Daily Progress" "$file"; then
              echo "Error: $file is missing Daily Progress section"
              exit 1
            fi
            
            if ! grep -q "### Weekly Summary" "$file"; then
              echo "Error: $file is missing Weekly Summary section"
              exit 1
            fi
            
            echo "$file passes structure check"
          done

      - name: Check Daily Updates
        run: |
          # Get current date in YYYY-MM-DD format
          TODAY=$(date +%Y-%m-%d)
          
          # Check if there are any updates today
          if ! git diff --name-only HEAD~1 HEAD | grep -q "weekly-progress.md"; then
            echo "Warning: No progress updates today"
            # Don't fail the build, just warn
          fi

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Progress check failed! Please ensure all required sections are present in your weekly progress files."
          echo "Required sections:"
          echo "- Week section (## Week)"
          echo "- Learning Objectives"
          echo "- Daily Progress"
          echo "- Weekly Summary"